### ISSUE TITLE
Error while executing both Pass1 and Pass2 at a time.

### ISSUE THREAD

**Issue by a9irudhh** [Harish-Patil-CSE/system-software-lab#1]
**$ gcc -o pass-1.exe pass-1.c utils.c && ./pass-1.exe && gcc -o pass-2.exe pass-2.c utils.c && ./pass-2.exe
Pass 1 of 2 of two completed successfully.
/usr/bin/ld: /tmp/cchsuR8w.o: in function `get_object_code_length':
pass-2.c:(.text+0xb65): undefined reference to `log2'
/usr/bin/ld: pass-2.c:(.text+0xb96): undefined reference to `ceil'
collect2: error: ld returned 1 exit status**

**Comment by Harish-Patil-CSE** [comment]
Linux requires explicitly linking `math.h`. Therefore compile with `-lm` argument
`gcc -o pass-1.exe pass-1.c utils.c -lm && ./pass-1.exe && gcc -o pass-2.exe pass-2.c utils.c -lm && ./pass-2.exe`
On windows, no such explicit linking is needed.
