### ISSUE TITLE
Need two additions to the program  

### ISSUE THREAD

**Issue by Swativbhat** [Harish-Patil-CSE/system-software-lab#5]
1. Text record should break for every `RESB` and `RESW` instructions.
2. `^`  or whitespace symbol to separate object codes in Text record.

**Comment by haristotle3** [comment]
Commit `90d2b3d` has resolved the first issue. New text record gets initialized for every non-consecutive `RESW` or `RESB` assembler directives in `OPCODE` field

**Comment by haristotle3** [comment]
Commit `75b9e03` resolved the starting address error of text record.

**Comment by haristotle3** [comment]
Commit `5e71499` solves second issue. Object codes are now separated by whitespaces in `object_programs.txt`
